---
- name: show ip interface brief 명령 실행
  hosts: all
  gather_facts: no

  tasks:
    - name: show ip interface brief 실행
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: 결과 출력
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"
